# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myChat(object):
    def setupUi(self, myChat):
        myChat.setObjectName("myChat")
        myChat.resize(680, 162)
        myChat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        myChat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatBox = QtWidgets.QFrame(myChat)
        self.chatBox.setGeometry(QtCore.QRect(40, 30, 493, 65))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatBox.sizePolicy().hasHeightForWidth())
        self.chatBox.setSizePolicy(sizePolicy)
        self.chatBox.setMinimumSize(QtCore.QSize(0, 65))
        self.chatBox.setMaximumSize(QtCore.QSize(16777215, 65))
        self.chatBox.setObjectName("chatBox")
        self._2 = QtWidgets.QHBoxLayout(self.chatBox)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(10)
        self._2.setObjectName("_2")
        spacerItem = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.chat = QtWidgets.QLabel(self.chatBox)
        self.chat.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat.sizePolicy().hasHeightForWidth())
        self.chat.setSizePolicy(sizePolicy)
        self.chat.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.chat.setFont(font)
        self.chat.setStyleSheet("border: 2px solid rgb(255, 170, 0);\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.chat.setObjectName("chat")
        self._2.addWidget(self.chat)
        self.me = QtWidgets.QFrame(self.chatBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.me.sizePolicy().hasHeightForWidth())
        self.me.setSizePolicy(sizePolicy)
        self.me.setMinimumSize(QtCore.QSize(60, 0))
        self.me.setObjectName("me")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.me)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.myImg = QtWidgets.QLabel(self.me)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myImg.sizePolicy().hasHeightForWidth())
        self.myImg.setSizePolicy(sizePolicy)
        self.myImg.setMinimumSize(QtCore.QSize(60, 60))
        self.myImg.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.myImg.setFont(font)
        self.myImg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.myImg.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(255, 170, 0);")
        self.myImg.setAlignment(QtCore.Qt.AlignCenter)
        self.myImg.setObjectName("myImg")
        self.verticalLayout_14.addWidget(self.myImg)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self._2.addWidget(self.me)

        self.retranslateUi(myChat)
        QtCore.QMetaObject.connectSlotsByName(myChat)

    def retranslateUi(self, myChat):
        _translate = QtCore.QCoreApplication.translate
        myChat.setWindowTitle(_translate("myChat", "Frame"))
        self.chat.setText(_translate("myChat", "user님이 입장하셨습니다."))
        self.myImg.setText(_translate("myChat", "img"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myChat = QtWidgets.QFrame()
    ui = Ui_myChat()
    ui.setupUi(myChat)
    myChat.show()
    sys.exit(app.exec_())
