# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userChat(object):
    def setupUi(self, userChat):
        userChat.setObjectName("userChat")
        userChat.resize(799, 166)
        userChat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        userChat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chatBox_2 = QtWidgets.QFrame(userChat)
        self.chatBox_2.setGeometry(QtCore.QRect(20, 50, 706, 65))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatBox_2.sizePolicy().hasHeightForWidth())
        self.chatBox_2.setSizePolicy(sizePolicy)
        self.chatBox_2.setMinimumSize(QtCore.QSize(0, 65))
        self.chatBox_2.setMaximumSize(QtCore.QSize(16777215, 65))
        self.chatBox_2.setObjectName("chatBox_2")
        self._9 = QtWidgets.QHBoxLayout(self.chatBox_2)
        self._9.setContentsMargins(0, 0, 0, 0)
        self._9.setSpacing(10)
        self._9.setObjectName("_9")
        self.User = QtWidgets.QFrame(self.chatBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.User.sizePolicy().hasHeightForWidth())
        self.User.setSizePolicy(sizePolicy)
        self.User.setMinimumSize(QtCore.QSize(60, 0))
        self.User.setObjectName("User")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.User)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.UserImg = QtWidgets.QLabel(self.User)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserImg.sizePolicy().hasHeightForWidth())
        self.UserImg.setSizePolicy(sizePolicy)
        self.UserImg.setMinimumSize(QtCore.QSize(60, 60))
        self.UserImg.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.UserImg.setFont(font)
        self.UserImg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.UserImg.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(255, 170, 0);")
        self.UserImg.setAlignment(QtCore.Qt.AlignCenter)
        self.UserImg.setObjectName("UserImg")
        self.verticalLayout_21.addWidget(self.UserImg)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem)
        self._9.addWidget(self.User)
        self.chat_8 = QtWidgets.QLabel(self.chatBox_2)
        self.chat_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_8.sizePolicy().hasHeightForWidth())
        self.chat_8.setSizePolicy(sizePolicy)
        self.chat_8.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.chat_8.setFont(font)
        self.chat_8.setStyleSheet("border: 2px solid rgb(255, 170, 0);\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.chat_8.setObjectName("chat_8")
        self._9.addWidget(self.chat_8)
        spacerItem1 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._9.addItem(spacerItem1)

        self.retranslateUi(userChat)
        QtCore.QMetaObject.connectSlotsByName(userChat)

    def retranslateUi(self, userChat):
        _translate = QtCore.QCoreApplication.translate
        userChat.setWindowTitle(_translate("userChat", "Frame"))
        self.UserImg.setText(_translate("userChat", "img"))
        self.chat_8.setText(_translate("userChat", "user님이 입장하셨습니다."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userChat = QtWidgets.QFrame()
    ui = Ui_userChat()
    ui.setupUi(userChat)
    userChat.show()
    sys.exit(app.exec_())
